language: node_js
node_js:
  - "10"

branches:
  only:
    - master

notifications:
  slack: is-utn-2019:MwfmDe6oNSAZsxfIcO5IZFpA

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test --watch=false --browsers=ChromeHeadless
  - ng build --prod --aot


after_success:
  - firebase deploy --token $FIREBASE_TOKEN
